/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assginmentjava3gd;

//import login.login;
import Util.Auth;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import loginform.login;
import org.apache.log4j.Logger;
import org.apache.xmlbeans.impl.schema.StscState;
import raven.alerts.MessageAlerts;
import raven.popup.GlassPanePopup;
import raven.popup.component.PopupCallbackAction;
import raven.popup.component.PopupController;

/**
 *
 * @author bfat
 */
public class view extends javax.swing.JFrame {

    Color DefaultColor, ClickColor;
    private boolean isFormOpen = false;
    public Major2 mj = new Major2();
    public student2 st = new student2();
    public class2 cl = new class2();
    public chart2 das = new chart2();

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        GlassPanePopup.install(this); // Dòng này cài đặt (install) GlassPanePopup vào JFrame hiện tại (this).
        FlatMacLightLaf.setup();
        phanquyen();
        dashboarddk();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // nghĩa là chương trình sẽ thoát hoàn toàn khi đóng cửa sổ. 
//        chart2 das = new chart2();

    }

    public void updateUserLabel(String email) {
        txtUser.setText(email);
    }
//    int width = 235;
//    int height = 704;
//
//    void OpenMenuBar() {
//        new Thread(new Runnable() {
//            @Override
//            public void run() {
//                for (int i = 0; i < width; i++) {
//                    Menuone.setSize(i, height);
//                    try {
//                        // mở từ từ 
//                        Thread.sleep(2);
//                    } catch (InterruptedException ex) {
//                        java.util.logging.Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//        }).start();
//    }
//
//    ;
//    // tao 
//    void CloseMenuBar() {
//        new Thread(new Runnable() {
//            @Override
//            public void run() {
//                for (int i = width; i > 0; i--) {
//                    Menuone.setSize(i, height);
//                    try {
//                        // mở từ từ 
//                        Thread.sleep(2);
//                    } catch (InterruptedException ex) {
//                        java.util.logging.Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//        }).start();
//    }
//
//    ;
    // phân quyền form cho admin và giáo viên và sinh viên 
    public void phanquyen() {
        if (Auth.isAdmin()) {
            return;
        } else if (Auth.isTeacher()) {
            MnQlLop.setEnabled(false);
            MnNganhvaMonHoc.setEnabled(false);
            MnBieuDo.setEnabled(false);
        } else if (Auth.isStudent()) {
            MnLichsuLop.setEnabled(false);
            MnQlMonHoc.setEnabled(false);
            MNqlSinhVien.setEnabled(false);
            MnQlNganh.setEnabled(false);
            MnNganhvaMonHoc.setEnabled(false);
            MnBieuDo.setEnabled(false);
            MnLsnganhhoc.setEnabled(false);
            MnSendMail.setEnabled(false);
        }
    }

    // chỉ cho admin và giáo viên coi đc dashdoard
    public void dashboarddk() {
        if (Auth.isAdmin()) {
            das.setBounds(0, 0, jdesktoppanel.getWidth(), jdesktoppanel.getHeight());
            this.setLocationRelativeTo(null);
            jdesktoppanel.removeAll();
            jdesktoppanel.add(das);
            jdesktoppanel.revalidate();
            jdesktoppanel.repaint();
            das.setVisible(true);
            menu.setText("Dashboard");
        } else if (Auth.isTeacher()) {
            das.setBounds(0, 0, jdesktoppanel.getWidth(), jdesktoppanel.getHeight());
            this.setLocationRelativeTo(null);
            jdesktoppanel.removeAll();
            jdesktoppanel.add(das);
            jdesktoppanel.revalidate();
            jdesktoppanel.repaint();
            das.setVisible(true);
            menu.setText("Dashboard");
        } else if (Auth.isStudent()) {
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnshow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jdesktoppanel = new javax.swing.JPanel();
        Menuone = new javax.swing.JPanel();
        txtUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        out = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menuuuu = new javax.swing.JLabel();
        lbusers = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MN1qlSinhVien = new javax.swing.JMenu();
        MNqlSinhVien = new javax.swing.JMenu();
        MnQlLop = new javax.swing.JMenu();
        MnLichsuLop = new javax.swing.JMenu();
        MnQlNganh = new javax.swing.JMenu();
        MnLsnganhhoc = new javax.swing.JMenu();
        MnQlMonHoc = new javax.swing.JMenu();
        MnQlDiem = new javax.swing.JMenu();
        MnNganhvaMonHoc = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MnDanhSach = new javax.swing.JMenu();
        MnXepHang = new javax.swing.JMenu();
        MnBieuDo = new javax.swing.JMenu();
        MnSendMail = new javax.swing.JMenu();
        MnSetting = new javax.swing.JMenu();
        MnCaiDat = new javax.swing.JMenu();
        MnDangXuat = new javax.swing.JMenu();

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Payment");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Total Earnings");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Dashboard");

        jTextField1.setText("Sreach for student");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Top Performer");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Attendance");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        btnshow.setText("show");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jdesktoppanel.setBackground(new java.awt.Color(255, 255, 255));
        jdesktoppanel.setPreferredSize(new java.awt.Dimension(1098, 300));

        javax.swing.GroupLayout jdesktoppanelLayout = new javax.swing.GroupLayout(jdesktoppanel);
        jdesktoppanel.setLayout(jdesktoppanelLayout);
        jdesktoppanelLayout.setHorizontalGroup(
            jdesktoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdesktoppanelLayout.setVerticalGroup(
            jdesktoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        Menuone.setBackground(new java.awt.Color(255, 255, 255));

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jLabel4.setText("Student Management");

        menu.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 0, 51));
        menu.setText("Form");
        menu.setToolTipText("");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        out.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/application.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 14)); // NOI18N
        jLabel5.setText("Welcome");

        javax.swing.GroupLayout MenuoneLayout = new javax.swing.GroupLayout(Menuone);
        Menuone.setLayout(MenuoneLayout);
        MenuoneLayout.setHorizontalGroup(
            MenuoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuoneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(out)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuoneLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(MenuoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuoneLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(MenuoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MenuoneLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuoneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuoneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(MenuoneLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuoneLayout.setVerticalGroup(
            MenuoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuoneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(out)
                .addGap(54, 54, 54))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        menuuuu.setBackground(new java.awt.Color(255, 255, 255));
        menuuuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3671806_menu_icon.png"))); // NOI18N
        menuuuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuuuuMouseClicked(evt);
            }
        });

        lbusers.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 24)); // NOI18N
        lbusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/6771575_building_education_school_university_icon.png"))); // NOI18N
        lbusers.setText("SCHOOL");

        Close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Close.setText("X");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(menuuuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                .addComponent(lbusers, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395)
                .addComponent(Close)
                .addGap(30, 30, 30))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuuuu)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbusers)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MN1qlSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1814113_add_more_plus_icon.png"))); // NOI18N
        MN1qlSinhVien.setText("SCHOOL");
        MN1qlSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MN1qlSinhVienMouseClicked(evt);
            }
        });

        MNqlSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/309036_student_education_study_icon.png"))); // NOI18N
        MNqlSinhVien.setText("Students");
        MNqlSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNqlSinhVienMouseClicked(evt);
            }
        });
        MN1qlSinhVien.add(MNqlSinhVien);

        MnQlLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20283_class_modules_icon.png"))); // NOI18N
        MnQlLop.setText("Class");
        MnQlLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnQlLopMouseClicked(evt);
            }
        });

        MnLichsuLop.setText("Lịch sử lớp học");
        MnLichsuLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnLichsuLopMouseClicked(evt);
            }
        });
        MnQlLop.add(MnLichsuLop);

        MN1qlSinhVien.add(MnQlLop);

        MnQlNganh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/major.png"))); // NOI18N
        MnQlNganh.setText("Major");
        MnQlNganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnQlNganhMouseClicked(evt);
            }
        });

        MnLsnganhhoc.setText("Lịch sử ngành học");
        MnLsnganhhoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnLsnganhhocMouseClicked(evt);
            }
        });
        MnQlNganh.add(MnLsnganhhoc);

        MN1qlSinhVien.add(MnQlNganh);

        MnQlMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8468584_education_test_exam_school_student_icon.png"))); // NOI18N
        MnQlMonHoc.setText("Subject");
        MnQlMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnQlMonHocMouseClicked(evt);
            }
        });
        MN1qlSinhVien.add(MnQlMonHoc);

        MnQlDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2824440_calculator_math_school_tool_icon.png"))); // NOI18N
        MnQlDiem.setText("Point");
        MnQlDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnQlDiemMouseClicked(evt);
            }
        });
        MN1qlSinhVien.add(MnQlDiem);

        MnNganhvaMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1519780_colorful_document_office_paper_school_icon.png"))); // NOI18N
        MnNganhvaMonHoc.setText("Major and Subject");
        MnNganhvaMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnNganhvaMonHocMouseClicked(evt);
            }
        });
        MN1qlSinhVien.add(MnNganhvaMonHoc);

        jMenuBar1.add(MN1qlSinhVien);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ranking.png"))); // NOI18N
        jMenu2.setText("Statistics");

        MnDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3069185_book_education_learn_school_icon.png"))); // NOI18N
        MnDanhSach.setText("List");
        MnDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnDanhSachMouseClicked(evt);
            }
        });
        jMenu2.add(MnDanhSach);

        MnXepHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ranking.png"))); // NOI18N
        MnXepHang.setText("Rank");
        MnXepHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnXepHangMouseClicked(evt);
            }
        });
        jMenu2.add(MnXepHang);

        MnBieuDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9165692_dashboard_graph_icon.png"))); // NOI18N
        MnBieuDo.setText("Dashboard");
        MnBieuDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnBieuDoMouseClicked(evt);
            }
        });
        jMenu2.add(MnBieuDo);

        MnSendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail.png"))); // NOI18N
        MnSendMail.setText("SendMail");
        MnSendMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnSendMailMouseClicked(evt);
            }
        });
        jMenu2.add(MnSendMail);

        jMenuBar1.add(jMenu2);

        MnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gear.png"))); // NOI18N
        MnSetting.setText("Setting");
        MnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnSettingMouseClicked(evt);
            }
        });

        MnCaiDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2620524_cv_employee_job_seeker_unemployee_icon.png"))); // NOI18N
        MnCaiDat.setText("Change password");
        MnCaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnCaiDatMouseClicked(evt);
            }
        });
        MnSetting.add(MnCaiDat);

        MnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/678146_arrow_exit_log out_right_icon.png"))); // NOI18N
        MnDangXuat.setText("Log out");
        MnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnDangXuatMouseClicked(evt);
            }
        });
        MnSetting.add(MnDangXuat);

        jMenuBar1.add(MnSetting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menuone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdesktoppanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menuone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jdesktoppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void menuuuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuuuuMouseClicked
        //OpenMenuBar();
    }//GEN-LAST:event_menuuuuMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void MNqlSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNqlSinhVienMouseClicked
        student2 st = new student2();

        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(st);  // Thêm đối tượng st
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            st.setVisible(true);  // Đảm bảo đối tượng st là visible
            menu.setText("Student");
            return;
        } else if (Auth.isTeacher()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(st);  // Thêm đối tượng st
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            st.setVisible(true);  // Đảm bảo đối tượng st là visible
            return;
        } else if (Auth.isStudent()) {
            // Sinh viên chỉ có quyền xem, vô hiệu hóa tất cả các button
            st.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_MNqlSinhVienMouseClicked

    private void MN1qlSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MN1qlSinhVienMouseClicked

    }//GEN-LAST:event_MN1qlSinhVienMouseClicked

    private void MnQlLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnQlLopMouseClicked
        class2 cl = new class2(); // cái này là jframe 
        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();
            jdesktoppanel.add(cl);  // Thêm đối tượng po
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            cl.setVisible(true);
            menu.setText("Class");
            return;
        } else if (Auth.isTeacher()) {
            cl.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (Auth.isStudent()) {
            jdesktoppanel.removeAll();
            jdesktoppanel.add(cl);  // Thêm đối tượng po
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            cl.setVisible(true);
            menu.setText("Class");
            return;
        }
    }//GEN-LAST:event_MnQlLopMouseClicked

    private void MnQlNganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnQlNganhMouseClicked
        Major2 ma = new Major2();

        menu.setText("Major");
        if (Auth.isAdmin()) {
            // Admin có toàn quyền, không cần hạn chế gì
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(ma);  // Thêm đối tượng ma
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            ma.setVisible(true);
            menu.setText("Major");
            return;
        } else if (Auth.isTeacher()) {
            // Giảng viên chỉ có thể xem và chỉnh sửa nhưng không có quyền xóa
            ma.setVisible(true);
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(ma);  // Thêm đối tượng ma
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            return;
        } else if (Auth.isStudent()) {
            // Sinh viên chỉ có quyền xem, vô hiệu hóa tất cả các button
            ma.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_MnQlNganhMouseClicked

    private void MnQlMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnQlMonHocMouseClicked
        subject2 sb = new subject2(); // cái này là jframe 
        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();
            jdesktoppanel.add(sb);  // Thêm đối tượng po
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            sb.setVisible(true);
            menu.setText("Subject");
            return;
        } else if (Auth.isTeacher()) {
            jdesktoppanel.removeAll();
            jdesktoppanel.add(sb);  // Thêm đối tượng po
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            sb.setVisible(true);
            menu.setText("Subject");
            return;
        } else if (Auth.isStudent()) {
            sb.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_MnQlMonHocMouseClicked

    private void MnQlDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnQlDiemMouseClicked
        point2 po = new point2(); // cái này là jframe 
        jdesktoppanel.removeAll();
        jdesktoppanel.add(po);  // Thêm đối tượng po
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        po.setVisible(true);
        menu.setText("Point");
    }//GEN-LAST:event_MnQlDiemMouseClicked

    private void MnDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnDanhSachMouseClicked
        list2 lt = new list2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(lt);  // Thêm đối tượng lt
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        lt.setVisible(true);
        menu.setText("List");
    }//GEN-LAST:event_MnDanhSachMouseClicked

    private void MnXepHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnXepHangMouseClicked
        Rank2 rank = new Rank2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(rank);  // Thêm đối tượng rank
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        rank.setVisible(true);
        menu.setText("Rank");
    }//GEN-LAST:event_MnXepHangMouseClicked

    private void MnBieuDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnBieuDoMouseClicked
        chart2 das = new chart2();
        if (Auth.isAdmin()) {
            das.setBounds(0, 0, jdesktoppanel.getWidth(), jdesktoppanel.getHeight());
            jdesktoppanel.removeAll();
            jdesktoppanel.add(das);
            jdesktoppanel.revalidate();
            jdesktoppanel.repaint();
            das.setVisible(true);
            menu.setText("Dashboard");
            return;
        } else if (Auth.isTeacher()) {
            das.setBounds(0, 0, jdesktoppanel.getWidth(), jdesktoppanel.getHeight());
            jdesktoppanel.removeAll();
            jdesktoppanel.add(das);
            jdesktoppanel.revalidate();
            jdesktoppanel.repaint();
            das.setVisible(true);
            menu.setText("Dashboard");
            return;
        } else if (Auth.isStudent()) {
            das.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_MnBieuDoMouseClicked

    private void MnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnSettingMouseClicked

    }//GEN-LAST:event_MnSettingMouseClicked

    private void MnCaiDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnCaiDatMouseClicked
        Setting2 st = new Setting2();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(st);  // Thêm đối tượng sbma
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        st.setVisible(true);
        menu.setText("Setting");


    }//GEN-LAST:event_MnCaiDatMouseClicked

    private void MnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnDangXuatMouseClicked
        int conf = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (conf == JOptionPane.YES_OPTION) {
            login login = new login();
            login.setVisible(true);
            login.pack();
            login.setLocationRelativeTo(null);
            this.dispose();
        }


    }//GEN-LAST:event_MnDangXuatMouseClicked

    private void MnSendMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnSendMailMouseClicked
        SendEmail send = new SendEmail();
        jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
        jdesktoppanel.add(send);  // Thêm đối tượng send
        jdesktoppanel.revalidate();  // Cập nhật lại giao diện
        jdesktoppanel.repaint();  // Vẽ lại giao diện
        send.setVisible(true);
        menu.setText("SendMail");
    }//GEN-LAST:event_MnSendMailMouseClicked

    private void MnNganhvaMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnNganhvaMonHocMouseClicked
        SubjectandMajor2 sbma = new SubjectandMajor2();
        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(sbma);  // Thêm đối tượng sbma
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            sbma.setVisible(true);
            menu.setText("SubjectandMajor");
            return;
        } else if (Auth.isTeacher()) {
            sbma.setVisible(true);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (Auth.isStudent()) {
            sbma.setVisible(true);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_MnNganhvaMonHocMouseClicked

    private void outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseClicked
        MessageAlerts.getInstance().showMessage("Bạn có muốn tắt hệ thống!!", "Descrition", MessageAlerts.MessageType.SUCCESS, MessageAlerts.YES_NO_OPTION, new PopupCallbackAction() {
            @Override
            public void action(PopupController pc, int i) {
                if (i == MessageAlerts.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

//         int conf = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
//         if(conf == JOptionPane.YES_OPTION){
//             System.exit(0);
//         }

    }//GEN-LAST:event_outMouseClicked

    private void MnLichsuLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnLichsuLopMouseClicked
        HistoryClass hs = new HistoryClass();
        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(hs);  // Thêm đối tượng hs
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            hs.setVisible(true);
            menu.setText("HistoryClass");
            return;
        } else if (Auth.isTeacher()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(hs);  // Thêm đối tượng hs
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            hs.setVisible(true);
            menu.setText("HistoryClass");
            return;
        } else if (Auth.isStudent()) {
            hs.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_MnLichsuLopMouseClicked

    private void MnLsnganhhocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnLsnganhhocMouseClicked
        HistoryMajor2 hsmj = new HistoryMajor2();
        if (Auth.isAdmin()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(hsmj);  // Thêm đối tượng hsmj
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            hsmj.setVisible(true);
            menu.setText("HistoryMajor2");
            return;
        } else if (Auth.isTeacher()) {
            jdesktoppanel.removeAll();  // Xóa các thành phần trước đó
            jdesktoppanel.add(hsmj);  // Thêm đối tượng hsmj
            jdesktoppanel.revalidate();  // Cập nhật lại giao diện
            jdesktoppanel.repaint();  // Vẽ lại giao diện
            hsmj.setVisible(true);
            menu.setText("HistoryMajor2");
            return;
        } else if (Auth.isStudent()) {
            hsmj.setVisible(false);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }


    }//GEN-LAST:event_MnLsnganhhocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        if (Auth.isLogin()) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {

                    new view().setVisible(true);
                }
            });
        } else {
            new login().setVisible(true);
            return;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JMenu MN1qlSinhVien;
    private javax.swing.JMenu MNqlSinhVien;
    private javax.swing.JPanel Menuone;
    private javax.swing.JMenu MnBieuDo;
    private javax.swing.JMenu MnCaiDat;
    private javax.swing.JMenu MnDangXuat;
    private javax.swing.JMenu MnDanhSach;
    private javax.swing.JMenu MnLichsuLop;
    private javax.swing.JMenu MnLsnganhhoc;
    private javax.swing.JMenu MnNganhvaMonHoc;
    private javax.swing.JMenu MnQlDiem;
    private javax.swing.JMenu MnQlLop;
    private javax.swing.JMenu MnQlMonHoc;
    private javax.swing.JMenu MnQlNganh;
    private javax.swing.JMenu MnSendMail;
    private javax.swing.JMenu MnSetting;
    private javax.swing.JMenu MnXepHang;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jdesktoppanel;
    private javax.swing.JLabel lbusers;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menuuuu;
    private javax.swing.JLabel out;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
